Fix: Remove optional input for maven verify
The repository is already set in checkout-gerrit-change-action
and not required to be passed.

Error:
Error: Invalid repository 'controller'. Expected format {owner}/{repo}.

Signed-off-by: Anil Belur <abelur@linuxfoundation.org>